#!/usr/bin/env bash

toClearSession=$(tmux ls | awk '{print substr($1, 1, length($1)-1)}' | fzf -m)

if [[ -z $toClearSession ]]; then
	exit 0
fi

for session in $toClearSession; do
	tmux kill-session -t $session
	echo "Session $session cleared"
done
